
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Jan 15 13:10:14 CET 2018
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 21;
  public static final int RCLOSE = 5;
  public static final int SOPEN = 6;
  public static final int DOUBLE_TYPE = 29;
  public static final int LT = 15;
  public static final int ELSE = 30;
  public static final int PLUS = 8;
  public static final int INT = 32;
  public static final int OR = 22;
  public static final int EQUAL = 12;
  public static final int WHILE = 25;
  public static final int SCLOSE = 7;
  public static final int STAR = 10;
  public static final int GCLOSE = 2;
  public static final int SLASH = 11;
  public static final int S = 13;
  public static final int NOT = 23;
  public static final int ELT = 19;
  public static final int IF = 24;
  public static final int GT = 16;
  public static final int ROPEN = 4;
  public static final int COMMA = 14;
  public static final int EGT = 20;
  public static final int EOF = 0;
  public static final int GOPEN = 3;
  public static final int MINUS = 9;
  public static final int PRINT = 26;
  public static final int error = 1;
  public static final int INT_TYPE = 28;
  public static final int LET = 17;
  public static final int VAR = 31;
  public static final int GET = 18;
  public static final int DOUBLE = 33;
  public static final int UMINUS = 27;
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[21]=new String("AND");
		TT[5]=new String("RCLOSE");
		TT[6]=new String("SOPEN");
		TT[29]=new String("DOUBLE_TYPE");
		TT[15]=new String("LT");
		TT[30]=new String("ELSE");
		TT[8]=new String("PLUS");
		TT[32]=new String("INT");
		TT[22]=new String("OR");
		TT[12]=new String("EQUAL");
		TT[25]=new String("WHILE");
		TT[7]=new String("SCLOSE");
		TT[10]=new String("STAR");
		TT[2]=new String("GCLOSE");
		TT[11]=new String("SLASH");
		TT[13]=new String("S");
		TT[23]=new String("NOT");
		TT[19]=new String("ELT");
		TT[24]=new String("IF");
		TT[16]=new String("GT");
		TT[4]=new String("ROPEN");
		TT[14]=new String("COMMA");
		TT[20]=new String("EGT");
		TT[0]=new String("EOF");
		TT[3]=new String("GOPEN");
		TT[9]=new String("MINUS");
		TT[26]=new String("PRINT");
		TT[1]=new String("error");
		TT[28]=new String("INT_TYPE");
		TT[17]=new String("LET");
		TT[31]=new String("VAR");
		TT[18]=new String("GET");
		TT[33]=new String("DOUBLE");
		TT[27]=new String("UMINUS");
	}
public String getTT(int i){return TT[i];}
}
