
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Jan 14 18:52:08 CET 2018
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RBS = 12;
  public static final int RBR = 10;
  public static final int PLUS = 5;
  public static final int VECTOR_VAR = 4;
  public static final int CM = 16;
  public static final int SCALAR_VAR = 3;
  public static final int PV = 14;
  public static final int EXP = 17;
  public static final int PT = 15;
  public static final int EQUALS = 13;
  public static final int EOF = 0;
  public static final int DIV = 7;
  public static final int MINUS = 6;
  public static final int CONST = 2;
  public static final int error = 1;
  public static final int PROD = 8;
  public static final int LBS = 11;
  public static final int LBR = 9;
  public static final int QP = 18;
  public static final int UMINUS = 19;
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[12]=new String("RBS");
		TT[10]=new String("RBR");
		TT[5]=new String("PLUS");
		TT[4]=new String("VECTOR_VAR");
		TT[16]=new String("CM");
		TT[3]=new String("SCALAR_VAR");
		TT[14]=new String("PV");
		TT[17]=new String("EXP");
		TT[15]=new String("PT");
		TT[13]=new String("EQUALS");
		TT[0]=new String("EOF");
		TT[7]=new String("DIV");
		TT[6]=new String("MINUS");
		TT[2]=new String("CONST");
		TT[1]=new String("error");
		TT[8]=new String("PROD");
		TT[11]=new String("LBS");
		TT[9]=new String("LBR");
		TT[18]=new String("QP");
		TT[19]=new String("UMINUS");
	}
public String getTT(int i){return TT[i];}
}
