
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Jan 14 18:55:09 CET 2018
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SOPEN = 3;
  public static final int PLUS = 5;
  public static final int EXPON = 9;
  public static final int EQUAL = 11;
  public static final int SCLOSE = 4;
  public static final int STAR = 7;
  public static final int POINT = 10;
  public static final int SVAR = 15;
  public static final int SCALAR = 2;
  public static final int SEMIC = 12;
  public static final int COMMA = 14;
  public static final int EOF = 0;
  public static final int DIV = 8;
  public static final int MINUS = 6;
  public static final int error = 1;
  public static final int VVAR = 16;
  public static final int QM = 13;
  public static final int UMINUS = 17;
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[3]=new String("SOPEN");
		TT[5]=new String("PLUS");
		TT[9]=new String("EXPON");
		TT[11]=new String("EQUAL");
		TT[4]=new String("SCLOSE");
		TT[7]=new String("STAR");
		TT[10]=new String("POINT");
		TT[15]=new String("SVAR");
		TT[2]=new String("SCALAR");
		TT[12]=new String("SEMIC");
		TT[14]=new String("COMMA");
		TT[0]=new String("EOF");
		TT[8]=new String("DIV");
		TT[6]=new String("MINUS");
		TT[1]=new String("error");
		TT[16]=new String("VVAR");
		TT[13]=new String("QM");
		TT[17]=new String("UMINUS");
	}
public String getTT(int i){return TT[i];}
}
