
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Jan 13 12:34:00 CET 2018
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 22;
  public static final int RCLOSE = 5;
  public static final int SOPEN = 6;
  public static final int DOUBLE_TYPE = 26;
  public static final int LT = 16;
  public static final int ELSE = 34;
  public static final int PLUS = 8;
  public static final int INT = 30;
  public static final int OR = 23;
  public static final int EQUAL = 12;
  public static final int WHILE = 28;
  public static final int SCLOSE = 7;
  public static final int STAR = 10;
  public static final int GCLOSE = 2;
  public static final int SLASH = 11;
  public static final int S = 13;
  public static final int NOT = 24;
  public static final int ELT = 20;
  public static final int P = 14;
  public static final int IF = 27;
  public static final int GT = 17;
  public static final int ROPEN = 4;
  public static final int COMMA = 15;
  public static final int EGT = 21;
  public static final int EOF = 0;
  public static final int GOPEN = 3;
  public static final int MINUS = 9;
  public static final int PRINT = 29;
  public static final int error = 1;
  public static final int INT_TYPE = 25;
  public static final int LET = 18;
  public static final int VAR = 32;
  public static final int GET = 19;
  public static final int UMINUS = 33;
  public static final int DOUBLE = 31;
}
