
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Jan 13 18:34:58 CET 2018
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CLOSE_B = 7;
  public static final int RULE_START = 3;
  public static final int OPEN_B = 6;
  public static final int ATOM = 8;
  public static final int EOF = 0;
  public static final int VAR = 9;
  public static final int POINT = 2;
  public static final int error = 1;
  public static final int COMMA = 4;
  public static final int INT_START = 5;
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[7]=new String("CLOSE_B");
		TT[3]=new String("RULE_START");
		TT[6]=new String("OPEN_B");
		TT[8]=new String("ATOM");
		TT[0]=new String("EOF");
		TT[9]=new String("VAR");
		TT[2]=new String("POINT");
		TT[1]=new String("error");
		TT[4]=new String("COMMA");
		TT[5]=new String("INT_START");
	}
public String getTT(int i){return TT[i];}
}
