
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Jan 13 16:01:27 CET 2018
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LS = 11;
  public static final int SEMICOLON = 9;
  public static final int GEN = 15;
  public static final int DATE = 17;
  public static final int AV = 12;
  public static final int LI = 10;
  public static final int SEPARATOR = 16;
  public static final int LETTER = 7;
  public static final int STRING = 5;
  public static final int COMMA = 8;
  public static final int SO = 13;
  public static final int EOF = 0;
  public static final int NUMBER = 6;
  public static final int ISBN = 3;
  public static final int error = 1;
  public static final int SEP_WRITER = 2;
  public static final int BO = 14;
  public static final int DPOINTS = 4;
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[11]=new String("LS");
		TT[9]=new String("SEMICOLON");
		TT[15]=new String("GEN");
		TT[17]=new String("DATE");
		TT[12]=new String("AV");
		TT[10]=new String("LI");
		TT[16]=new String("SEPARATOR");
		TT[7]=new String("LETTER");
		TT[5]=new String("STRING");
		TT[8]=new String("COMMA");
		TT[13]=new String("SO");
		TT[0]=new String("EOF");
		TT[6]=new String("NUMBER");
		TT[3]=new String("ISBN");
		TT[1]=new String("error");
		TT[2]=new String("SEP_WRITER");
		TT[14]=new String("BO");
		TT[4]=new String("DPOINTS");
	}
public String getTT(int i){return TT[i];}
}
